### ISSUE TITLE
log dirs override doesn't actually work despite what docs say

### ISSUE THREAD

**Issue by inadarei** [StreamingMicroservicesPlatform/docker-kafka#5]
Getting this error:

```
FATAL  (kafka.Kafka$)
kafka-broker_1     | joptsimple.UnrecognizedOptionException: override log.dirs is not a recognized option
kafka-broker_1     | 	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
kafka-broker_1     | 	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
kafka-broker_1     | 	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
kafka-broker_1     | 	at joptsimple.OptionParser.parse(OptionParser.java:396)
kafka-broker_1     | 	at kafka.Kafka$.getPropsFromArgs(Kafka.scala:47)
kafka-broker_1     | 	at kafka.Kafka$.main(Kafka.scala:81)
kafka-broker_1     | 	at kafka.Kafka.main(Kafka.scala)
```

My docker-compose:

```yaml
 kafka-broker:
    image: solsson/kafka
    ports:
      - '9092:9092'
    volumes:
      - kafka_solsson:/var/lib/kafka/data
    entrypoint: ./bin/kafka-server-start.sh
    command:
      - config/server.properties
      - --override
      -   zookeeper.connect=zookeeper:2181
      - --override 
          log.dirs=/var/lib/kafka/data/topics
      - --override
      -   broker.id=0
      # unlike Kubernetes StatefulSet, compose gives containers a random hostname (leading to redirects to a hex name)
      - --override
      -   advertised.listener=PLAINTEXT://kafka-0:9092   

volumes:
  kafka_solsson:    
```
